### ISSUE TITLE
Use library nginx?

### ISSUE THREAD

**Issue by VeeeneX** [dockette/nginx#2]
It would be nice to use library/nginx :)

**Comment by f3l1x** [comment]
What do you mean? Do you mean official base image nginx? I don't want it, I like to use debian based nginx and do-it by my own.

**Comment by VeeeneX** [comment]
Yes, but that's only preference, ok so closing

**Comment by f3l1x** [comment]
@VeeeneX Yep. Thanks for understanding. :-)
